[package]
name = "bazuka"
version = "0.1.0"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"], optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
futures = "0.3"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
leveldb = "0.8.6"
home = "0.5.3"
db-key = "0.0.5"
ff = { version = "0.11", features = ["derive"] }
sha3 = "0.10.0"
bincode = "1.3.3"
rand = "0.8.5"
thiserror = "1.0"

[features]
node = ["tokio", "hyper"]
