[package]
name = "bazuka"
version = "0.1.0"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>"]
edition = "2018"

[dependencies]
libp2p = { version = "0.41.0", optional = true }
futures = "0.3.17"
vrf = "0.2.3"
bls-signatures = "0.11.1"
