name: Bazuka

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Bazuka
      run: docker build -t bazuka .
    - name: Test Bazuka
      run: docker run bazuka cargo test --release --features node
