name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Bazuka
      run: docker build . --file Dockerfile --tag bazuka:$(date +%s)
    - name: Test Bazuka
      run: docker run bazuka cargo test --release --features node
